### ISSUE TITLE
Port stochastic scenarios

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#13251]
The Drake developers at TRI have the following capabilities in our internal repositories:
- specify random distributions and transforms in C++, Python, and YAML,
- specify constraints on pose, generalized position, and vector direction in C++, Python, and YAML,
- populate these values into a simulation's initial conditions and diagram-level constraints.

In principle, we are happy to share it, but making it public takes time and we have not yet prioritized it. Please upvote it by adding a "thumbs up" reaction to this comment if you want us to know that you are keen.

Here's an illustration of how it could be used to specify a simulation:
```yaml
# An example scenario for acrobot, with randomness.
one_example:
  controller_params: !UniformVector
    min: [4, 40, 4, 0.9e3]
    max: [6, 60, 6, 1.1e3]
  initial_state: !UniformVector
    min: [1.1, -0.1, -0.1, -0.1]
    max: [1.3, 0.1, 0.1, 0.1]
  t_final: 30.0
  tape_period: 0.05
```
