### ISSUE TITLE
Issue with drake_werror and drake_cc_vector_gen_library

### ISSUE THREAD

**Issue by cjds** [RobotLocomotion/drake#14068]
Trying to use `drake_cc_vector_gen_library`  in an external Drake project and I run into the following error

```
ERROR: Analysis of target '//double_pendulum:energy_shaping' failed; build aborted: no such package 'tools': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
```

When I create the folder tools and the BUILD file

```
ERROR: While resolving configuration keys for //double_pendulum:pendulum_vector_types: no such target '//tools:drake_werror': target 'drake_werror' not declared in package 'tools' defined by /root/doublependulum/tools/BUILD
ERROR: Analysis of target '//double_pendulum:energy_shaping' failed; build aborted: no such target '//tools:drake_werror': target 'drake_werror' not declared in package 'tools' defined by /root/doublependulum/tools/BUILD
```
Probably coming from 

https://github.com/RobotLocomotion/drake/blob/7c06b9127077e10aa8444ba61aacae687408d3b6/tools/skylark/drake_cc.bzl#L66

I think

Repro using

```
drake_cc_vector_gen_library(
    name = "pendulum_vector_types",
    srcs = [
      "pendulum_state_named_vector.yaml",
    ],
    visibility = ["//visibility:public"],
)

```

and `pendulum_state_named_vector.yaml`
```
namespace: drake::examples::pendulum
elements:
  -
    name: theta
    doc: The angle of the pendulum.
    doc_units: radians
    default_value: 0.0
  -
    name: thetadot
    doc: The angular velocity of the pendulum.
    doc_units: radians/sec
    default_value: 0.0

```
