### ISSUE TITLE
model_directives: Going from single arm to multi-arm can be weird?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#14977]
I had some directives that, as standalone, were totes fine. However, I factored them into a separate file, and used `//add_directives/@model_namespace`, but found a discrepancy that caused some errors (which I needed to use `pydrake.common.set_log_level("trace")` to suss out).

*Still to figure out*: I'm not sure if I'm finding this b/c now `panda_origin` is non-unique (hence needing scoped name, which was always weird), or if there's actually an inconsistency btw `//add_directives` without or with `@model_namespace` set.

---

Before, I had something like this:
```yaml
directives:
- add_model:
    name: my_table
    file: package://.../my_table.sdf
- add_frame:
    name: panda_origin
    X_PF:
      base_frame: my_table::table_top_center
      ...
- add_model:
    name: panda
    file: package://franka_description/urdf/panda_arm.urdf
- add_weld:
    parent: panda_origin
    child: panda::panda_link0
```

And then I put that stuff in its own directive file, `add_single_arm_for_my_thing.yaml`, and then incorporated them as so:
```yaml
directives:
- add_model_instance:
    name: right
- add_directives:
    model_namespace: right
    file: package://anzu/models/visuomotor/add_single_panda_for_maverick.yaml
# Same thing for left.
```

However, when I did this, it basically indicated that `right::panda_origin` did not exist; instead, it needed to be spelled as `right::my_table::panda_origin`.

To fix (or workaround?), I just explicitly assigned the frame to the `panda` instance itself:
```
- add_frame:
   name: panda::origin
    X_PF:
      base_frame: my_table::table_top_center
      ...
```
