### ISSUE TITLE
sdformat: Should attempt migration from model directives; if sufficient, deprecate model directives

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#15948]
As follow-up from #15522. My plan is that this would happen after #15613 (and perhaps a more general version of that issue).

Suggested steps:

- Ensure that SDFormat usage in Drake can express basic *construction* that is (almost) equivalent to what we can express with model directives (ignoring distributions atm)
  - Will require reformulation for "leaky" scope that model directives allow vs. encapsulation, so welding "add-ons" will need to be done differently
- Possibly support drake-custom tags for defining distributions, or provide alternative design + implementation (e.g. externally define distributions)

FYI @jwnimmer-tri @ggould-tri

**Comment by aaronchongth** [comment]
After some experiments with the tests in `multibody/parsing/test/process_model_directives_test`, there have been some findings,

* [explicitly resolving a frame by namespacing its name](https://github.com/aaronchongth/drake/blob/aaron/deprecate-model-directives/multibody/parsing/test/process_model_directives_test/add_scoped_sub.yaml#L19-L24) is not supported and not needed, hence they will be commented out,
```
- add_frame:
    # This will explicitly resolve to the `simple_model` instance.
    name: simple_model::sub_added_frame_explicit
    X_PF:
      base_frame: simple_model::frame
      translation: [10, 20, 30]
```

* conversion of [`add_scoped_sub.yaml` ](https://github.com/aaronchongth/drake/blob/aaron/deprecate-model-directives/multibody/parsing/test/process_model_directives_test/add_scoped_sub.yaml) to [`add_scoped_sub.sdf`](https://github.com/aaronchongth/drake/blob/aaron/deprecate-model-directives/multibody/parsing/test/process_model_directives_test/add_scoped_sub.sdf) is partially successful
  * tests are passing and additional comparison tests too, https://github.com/aaronchongth/drake/blob/aaron/deprecate-model-directives/multibody/parsing/test/process_model_directives_test.cc#L69-L130
  * however when parsing just `add_scoped_sub.sdf` in `drake`, the number of bodies is no longer 2, as there is the overarching model `add_scoped_sub` which contains the model instances `simple_model` and `extra_model`
```
<model name="add_scoped_sub">
  <include>
    <name>simple_model</name>
    ...
  </include>
  <include>
    <name>extra_model</name>
    ...
  </include>
  ...
</model>
```

* At the moment, it seems that `sdformat` is unable to replicate an [unscoped include](https://github.com/aaronchongth/drake/blob/aaron/deprecate-model-directives/multibody/parsing/test/process_model_directives_test/add_scoped_top.yaml#L9-L22),
  * assuming `add_scoped_top.sdf` will contain a `world` instead of a `model` since there was a mention of a [`world` frame](https://github.com/aaronchongth/drake/blob/aaron/deprecate-model-directives/multibody/parsing/test/process_model_directives_test/add_scoped_top.yaml#L15)
  * merge include of a model into a world is currently not supported, hence there will always be a scope of the included model
```
# No namespace.
# N.B. If this were added after the namespaced instances, `simple_model_origin`
# would cause a failure because it appears in multiple model instances.
- add_frame:
    name: simple_model_origin
    X_PF:
      base_frame: world
- add_directives:
    file: package://process_model_directives_test/add_scoped_sub.yaml
- add_frame:
    name: simple_model::top_added_frame
    X_PF:
      base_frame: simple_model::sub_added_frame
      translation: [5, 10, 15]
```
  * with the snippet above, ideally we would like
```
<world name="add_scoped_top">
  <model name="simple_model" />
  <model name="extra_model" />
</world>
```
  * but we will achieve
```
<world name="add_scoped_top">
  <model name="add_scoped_sub">
    <model name="simple_model" />
    <model name="extra_model" />
  </model>
</world>
```
