### ISSUE TITLE
access to `drake:collision_filter_group` parsed in URDFs

### ISSUE THREAD

**Issue by sadraddini** [RobotLocomotion/drake#20662]
**Is your feature request related to a problem? Please describe.**
`drake:collision_filter_group` are useful in urdfs to filter collisions between the declared group and _previously declared groups_ (in the same urdf). 

However, there is no way to access these groups after when the urdf files are parsed. This poses some problems:
1. If the user wants to declare a collision filter between `groupA` from `urdfA` and `groupB` from `urdfB`, it has to copy/paste all the members into their code. The `add_collision_filter_group` in `ModelDirective` comes close to a solution`:
```
  - add_collision_filter_group:
      name: foo
      members: [modelA::link1, modelA::link2, ..., modelA::linkN]
      ignored_collision_filter_groups: [modelB::groupB]
```
But one has to still write all members of A by hand. We don't have something like the following, it won't work:
```
  - add_collision_filter_group:
      name: foo
      members: [modelA::groupA]
      ignored_collision_filter_groups: [modelB::groupB]
```
it will throw `RuntimeError: error: body with name 'modelA::groupA' not found` because indeed groupA is not a body, but a group of bodies. If you replace `[modelA::groupA]` with `[modelA::link1]`, it will work (so it understands `ignored_collision_filter_groups: [modelB::groupB]` 

**Describe the solution you'd like**
The solution I **love** is to have something like `std::vector<BodyIndex> GetCollisionFilterGroupByName()`.
It would be so useful not only for default collision filtering, but also for declaring other collision filters using various `CollisionChecker` objects, or declare, for instance, CollisionChecker paddings between two groups of bodies. 

For example, in the URDF we would only have:
```
  <drake:collision_filter_group name="foo">
    <drake:member link="link1"/>
    <drake:member link="link 2"/>
    ...
    <drake:member link="linkN"/>
  </drake:collision_filter_group>
```
And then one can grab the bodies in `foo` and `foo2` in the API to do whatever they want to do with it.

**Describe alternatives you've considered**
`AddCollisionFilterGroup` in ModelDirectives would have a field `group_members`
```
  - add_collision_filter_group:
      name: foo
      members: []
      group_members: [modelA::groupA]
      ignored_collision_filter_groups: [modelB::groupB]
```
And this will filter all bodies in `modelA::groupA` with `modelB::groupB`
