### ISSUE TITLE
yaml_to_obj: error when different lanes have overlapping points

### ISSUE THREAD

**Issue by basicNew** [RobotLocomotion/drake#5804]
Even though it is not a common case, when dealing with arbitrary road geometries, two different roads may have an overlapping control point, which causes `yaml_to_obj` to fail. To depict the situation, the following three monolane files are valid:

``` 
# -*- yaml -*-
---
# distances are meters; angles are degrees.
maliput_monolane_builder:
  id: Cross
  lane_bounds: [-2, 2]
  driveable_bounds: [-4, 4]
  position_precision: 0.01
  orientation_precision: 0.5
  points:
    s1_1_1:
      xypoint: [-50.0, 0.0, 0.0]
      zpoint: [0.0, 0, 0, 0]
    s1_1_2:
      xypoint: [50.0, 0.0, 0.0]
      zpoint: [0.0, 0, 0, 0]
    s2_1_1:
      xypoint: [0.0, 50.0, -90.0]
      zpoint: [0.0, 0, 0, 0]
    s2_1_2:
      xypoint: [0.0, -50.0, -90.0]
      zpoint: [0.0, 0, 0, 0]
  connections:
    s1_1_1-s1_1_2: {start: points.s1_1_1, length: 100.0, explicit_end: points.s1_1_2}
    s2_1_1-s2_1_2: {start: points.s2_1_1, length: 100.0, explicit_end: points.s2_1_2}
  groups: {}
```
![screenshot from 2017-04-12 11 32 58](https://cloud.githubusercontent.com/assets/4070228/24963428/efb65a14-1f74-11e7-8b0c-2266c713bf51.png)

```
# -*- yaml -*-
---
# distances are meters; angles are degrees.
maliput_monolane_builder:
  id: Cross
  lane_bounds: [-2, 2]
  driveable_bounds: [-4, 4]
  position_precision: 0.01
  orientation_precision: 0.5
  points:
    s1_1_1:
      xypoint: [-50.0, 0.0, 0.0]
      zpoint: [0.0, 0, 0, 0]
    s1_1_2:
      xypoint: [0.0, 0.0, 0.0]
      zpoint: [0.0, 0, 0, 0]
    s1_1_3:
      xypoint: [50.0, 0.0, 0.0]
      zpoint: [0.0, 0, 0, 0]    
    s2_1_1:
      xypoint: [0.0, 50.0, -90.0]
      zpoint: [0.0, 0, 0, 0]
    s2_1_2:
      xypoint: [0.0, -50.0, -90.0]
      zpoint: [0.0, 0, 0, 0]
  connections:
    s1_1_1-s1_1_2: {start: points.s1_1_1, length: 50.0, explicit_end: points.s1_1_2}
    s1_1_2-s1_1_3: {start: points.s1_1_2, length: 50.0, explicit_end: points.s1_1_3}
    s2_1_1-s2_1_2: {start: points.s2_1_1, length: 100.0, explicit_end: points.s2_1_2}
  groups: {}
```

![screenshot from 2017-04-12 11 32 49](https://cloud.githubusercontent.com/assets/4070228/24963462/0bcbbc26-1f75-11e7-87d6-c293362ea81a.png)

```
# -*- yaml -*-
---
# distances are meters; angles are degrees.
maliput_monolane_builder:
  id: Cross
  lane_bounds: [-2, 2]
  driveable_bounds: [-4, 4]
  position_precision: 0.01
  orientation_precision: 0.5
  points:
    s1_1_1:
      xypoint: [-50.0, 0.0, 0.0]
      zpoint: [0.0, 0, 0, 0]
    s1_1_2:
      xypoint: [50.0, 0.0, 0.0]
      zpoint: [0.0, 0, 0, 0]
    s2_1_1:
      xypoint: [0.0, 50.0, -90.0]
      zpoint: [0.0, 0, 0, 0]
    s2_1_2:
      xypoint: [0.0, 0.0, -90.0]
      zpoint: [0.0, 0, 0, 0]
    s2_1_3:
      xypoint: [0.0, -50.0, -90.0]
      zpoint: [0.0, 0, 0, 0]  
  connections:
    s1_1_1-s1_1_2: {start: points.s1_1_1, length: 100.0, explicit_end: points.s1_1_2}
    s2_1_1-s2_1_2: {start: points.s2_1_1, length: 50.0, explicit_end: points.s2_1_2}
    s2_1_2-s2_1_3: {start: points.s2_1_2, length: 50.0, explicit_end: points.s2_1_3}
  groups: {}
```

![screenshot from 2017-04-12 11 34 40](https://cloud.githubusercontent.com/assets/4070228/24963506/2a3a2094-1f75-11e7-9f75-b208a81d2008.png)

However, the following monolane definition fails with:
```
[2017-04-12 11:35:25.438] [console] [info] Loading road geometry.
[2017-04-12 11:35:25.441] [console] [error] Lane l:s1_1_2-s1_1_3[start] orientation is off by 2.22144.
[2017-04-12 11:35:25.441] [console] [error] Lane l:s1_1_1-s1_1_2[end] orientation is off by 2.22144.
abort: failure at drake/automotive/maliput/monolane/builder.cc:308 in Build(): assertion 'failures.size() == 0' failed.
Aborted (core dumped)
```

```
# -*- yaml -*-
---
# distances are meters; angles are degrees.
maliput_monolane_builder:
  id: Cross
  lane_bounds: [-2, 2]
  driveable_bounds: [-4, 4]
  position_precision: 0.01
  orientation_precision: 0.5
  points:
    s1_1_1:
      xypoint: [-50.0, 0.0, 0.0]
      zpoint: [0.0, 0, 0, 0]
    s1_1_2:
      xypoint: [0.0, 0.0, 0.0]
      zpoint: [0.0, 0, 0, 0]
    s1_1_3:
      xypoint: [50.0, 0.0, 0.0]
      zpoint: [0.0, 0, 0, 0]    
    s2_1_1:
      xypoint: [0.0, 50.0, -90.0]
      zpoint: [0.0, 0, 0, 0]
    s2_1_2:
      xypoint: [0.0, 0.0, -90.0]
      zpoint: [0.0, 0, 0, 0]
    s2_1_3:
      xypoint: [0.0, -50.0, -90.0]
      zpoint: [0.0, 0, 0, 0]  
  connections:
    s1_1_1-s1_1_2: {start: points.s1_1_1, length: 50.0, explicit_end: points.s1_1_2}
    s1_1_2-s1_1_3: {start: points.s1_1_2, length: 50.0, explicit_end: points.s1_1_3}
    s2_1_1-s2_1_2: {start: points.s2_1_1, length: 50.0, explicit_end: points.s2_1_2}
    s2_1_2-s2_1_3: {start: points.s2_1_2, length: 50.0, explicit_end: points.s2_1_3}
  groups: {}
```

If I do a slight change in one of the points then it works again:

```
# -*- yaml -*-
---
# distances are meters; angles are degrees.
maliput_monolane_builder:
  id: Cross
  lane_bounds: [-2, 2]
  driveable_bounds: [-4, 4]
  position_precision: 0.01
  orientation_precision: 0.5
  points:
    s1_1_1:
      xypoint: [-50.0, 0.0, 0.0]
      zpoint: [0.0, 0, 0, 0]
    s1_1_2:
      xypoint: [0.0, 0.1, 0.0]
      zpoint: [0.0, 0, 0, 0]
    s1_1_3:
      xypoint: [50.0, 0.0, 0.0]
      zpoint: [0.0, 0, 0, 0]    
    s2_1_1:
      xypoint: [0.0, 50.0, -90.0]
      zpoint: [0.0, 0, 0, 0]
    s2_1_2:
      xypoint: [0.0, 0.0, -90.0]
      zpoint: [0.0, 0, 0, 0]
    s2_1_3:
      xypoint: [0.0, -50.0, -90.0]
      zpoint: [0.0, 0, 0, 0]  
  connections:
    s1_1_1-s1_1_2: {start: points.s1_1_1, length: 50.1, explicit_end: points.s1_1_2}
    s1_1_2-s1_1_3: {start: points.s1_1_2, length: 49.9, explicit_end: points.s1_1_3}
    s2_1_1-s2_1_2: {start: points.s2_1_1, length: 50.0, explicit_end: points.s2_1_2}
    s2_1_2-s2_1_3: {start: points.s2_1_2, length: 50.0, explicit_end: points.s2_1_3}
  groups: {}
```
![screenshot from 2017-04-12 11 36 27](https://cloud.githubusercontent.com/assets/4070228/24963600/6b401968-1f75-11e7-9562-2a4ec85aa94e.png)

So I was wondering if this is the intended behavior or maybe a bug in the tool.
